name: 'Install packages'
description: 'Install required packages'

runs:
  using: "composite"
  steps:
    # Common Linux dependencies
    - name: Install Linux Dependencies
      shell: bash
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install ninja-build \
          libasound2-dev \
          libpulse-dev \
          libdbus-1-dev \
          libudev-dev \
          libx11-dev \
          libxext-dev \
          libxrandr-dev \
          libxrender-dev \
          libxinerama-dev \
          libxi-dev \
          libxcursor-dev \
          libxfixes-dev \
          libxss-dev \
          libxkbcommon-dev \
          libwayland-dev \
          libdrm-dev \
          libgbm-dev \
          libegl1-mesa-dev \
          libgl1-mesa-dev \
          libjpeg-dev \
          libpng-dev \
          zlib1g-dev
        # https://github.com/llvm/llvm-project/issues/78354
        sudo sysctl vm.mmap_rnd_bits=28

    # Also see https://github.com/actions/runner-images/discussions/9446#discussioncomment-8668538
    - name: Install Clang ${{ matrix.clang_ver }}
      if: runner.os == 'Linux' && matrix.runs_msan == true
      # renovate: datasource=github-tags depName=nick-fields/retry versioning=loose
      uses: nick-fields/retry@v3
      with:
        shell: bash
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x ./llvm.sh
          sudo ./llvm.sh ${{ matrix.clang_ver }}

    - name: Install libc++ (Linux Clang ${{ matrix.clang_ver }})
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_msan == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends libc++-${{ matrix.clang_ver }}-dev libc++abi-${{ matrix.clang_ver }}-dev

    - name: Install valgrind
      shell: bash
      if: runner.os == 'Linux' && matrix.runs_valgrind == true
      run: |
        # sudo apt-get update
        sudo apt-get install --no-install-recommends valgrind
